### ISSUE TITLE
Links disapears when clicking around on entities on my chart

### ISSUE THREAD

**Issue by stvdo** [i2group/notebook-sdk#12]
Good afternoon,

I updated to i2 Analyze 4.4.3 and the containers version 2.8.0.

After that I noticed a strange behavior on my chart. When I click on a entity some links will appear while other links will disappear.

![image](https://github.com/i2group/notebook-sdk/assets/52672945/eaf8a7ad-23ca-49ba-8748-cc31383d7b34)

When I select a camera some links are added to the chart
![image](https://github.com/i2group/notebook-sdk/assets/52672945/dbc3772c-2199-4de7-9e8e-ab18e17face2)

**Comment by Tim-Mawson-i2** [comment]
Hi @sdorresteijn88 that looks like a rendering issue (the links exist, they're not being drawn for some reason) - could you tell me some information about the system you're running on,:

1. Make and model of the system - can you try updating your graphics drivers?
2. Which browser you're running on - does the problem still occur if you use a different browser?
3. Opening DevTools in the browser and posting what you see in the console (particularly any diagnostic info or errors).
4. Sharing a screenshot of the information at https://webglreport.com/?v=1 and https://webglreport.com/?v=2
5. Is the problem consistent? Does it start occurring after a certain number of items are on the chart? Does a reload of the page make any difference?

**Comment by Tim-Mawson-i2** [comment]
Also note, as a *temporary* work-around you can force the use of an alternative renderer (which may bypass what ever issue is causing the problems you're seeing) by specifying it in the URL: https://i2analyze.eia:9443/opal/?renderer=canvas/#/charts Note that the alternative option may have performance issues for very large charts.

**Comment by stvdo** [comment]
@Tim-Mawson-i2 
1. Dell Precision 5550, the drivers are up to date
2. Chrome 121.0.6167.85, it happens also in Firefox 121.0 and in Edge 120.0.2210.144
3. Nothing special when I click around between entities on the chart
![image](https://github.com/i2group/notebook-sdk/assets/52672945/d7b3ffe6-8e6f-479a-abd9-14ca62d58eeb)
4. See below
![image](https://github.com/i2group/notebook-sdk/assets/52672945/b8c23415-4147-4607-b8b7-f0d3a7baae67)
![image](https://github.com/i2group/notebook-sdk/assets/52672945/3336eb76-15a7-413a-9ed2-4d00d6b3f77d)
5. With 34 entities and 24 links it works fine, but with 53 entities and 50 links it goes wrong.
6. I tested the alternative renderer, that works perfect.

I added system match rules for persons and vehicle recently, so entities are combine (after the update to the latest version). Can it be related with this that the rendering will break?

**Comment by Tim-Mawson-i2** [comment]
Thanks for all the detailed information, that helps. System, browser and reports all look fine and similar to systems we've tested 4.4.3 on, so I'm thinking that maybe it could be the match rules. You could try moving back to 4.4.2 and try combining those entities to see if a similar issue occurs - that would rule our the rendering backend and point to something that's happening when those entities are combined. I'll try and reproduce it at my end by running some match rules here.

**Comment by Tim-Mawson-i2** [comment]
Did you try reloading the problem chart?

**Comment by stvdo** [comment]
I have tested it quite often in 4.4.2 and didn't have this issues. It's hard to go back because I am running it in Docker containers, than I have to downgrade that as well. The combined entities was on of the reasons I did the update:)

I tried reloading, but that didn't help.

**Comment by Tim-Mawson-i2** [comment]
Could I ask you to post a trace of the network calls when the chart is loaded. It's done via saving a `.har` file from the browser Devtools Network tab. Once the tab is open, reload the page (`F5`) and then after the chart has loaded, right click on the Network Devtools pane and select "Save all as HAR with content" from the popup-menu:

![image](https://github.com/i2group/notebook-sdk/assets/97094232/0bebd797-09da-4aaf-a586-db057b054e74)

**Comment by stvdo** [comment]
[i2analyze.eia.har.zip](https://github.com/i2group/notebook-sdk/files/14066404/i2analyze.eia.har.zip)

**Comment by Tim-Mawson-i2** [comment]
We've checked through the responses and I've managed to "load" the chart into my local dev environment. Unfortunately, it's rendering absolutely fine and we can't find anything that looks out-of-place, which is obviously not ideal for us trying to track down exactly what's happening on your machine.

**Comment by Tim-Mawson-i2** [comment]
In the meantime I'll get this escalated, so we can track it and continue working on finding out what's going on.

**Comment by stvdo** [comment]
@Tim-Mawson-i2 too bad it can't be reproduced. Is there anything else that would help? E.g. would you like to take a look on my laptop?

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88 

I have been chatting with Tim on this and what you have here does seem to be product related not SDK related so can you raise a case for this through the normal support channels.  If you just include a link to this issue here and say that dev are already involved and agree it is a product issue then we can escalate it quickly and I will let Support know to expect it.

Cheers

**Comment by Tim-Mawson-i2** [comment]
@sdorresteijn88 Just to let you know, we've made some progress on this issue after managing to reproduce it on a machine with similar graphics hardware (Intel UHD)

**Comment by stvdo** [comment]
@Tim-Mawson-i2 thanks for the update! Good to hear that you were able to reproduce the issue!
