### ISSUE TITLE
Download all as .xlsx not working

### ISSUE THREAD

**Issue by stvdo** [i2group/notebook-sdk#13]
Good afternoon,

For the other issue I would like to export my data to Excel to share it. But this isn't working.

![image](https://github.com/i2group/notebook-sdk/assets/52672945/ced88b50-0066-4b32-9815-da03af52df5f)

When I click on the top right button 'Download all as .xlsx' I expect that all the 53 entities and the 50 links will be exported to Excel. But nothing happen.

In the console I got this error.
![image](https://github.com/i2group/notebook-sdk/assets/52672945/1976f2b0-e140-45b5-be6c-a4874b0622ab)

The 'Download as .xlsx' works fine, but than only 1 entity type is exported.

**Comment by Anthony-Johnson-i2** [comment]
HI @sdorresteijn88 

As his is  related to product functionality not the SDK can you raise this as a case please in the usual way.
We have managed to reproduce this issue..
As with issue 12 you can let support know that development is aware of this  so it can be escalated quickly.

Cheers

**Comment by stvdo** [comment]
Thanks a lot, I'll raise a support case for this.

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88  
This seems a bit back to front compared to our normal workflow but...
I was waiting for your case to arrive on this so that we could escalate it and process the fix for you but we have not seen it yet.
Are you intending to create it?
Cheers

**Comment by stvdo** [comment]
@Anthony-Johnson-i2 sorry I forgot to do this. The case is #00016907
