### ISSUE TITLE
Matching Entities with same ID

### ISSUE THREAD

**Issue by Timon-IW** [i2group/notebook-sdk#15]
Hello,

I'm not sure if I'm blind or just don't understand something, but I want to match the same entity when I add one with a plugin.
Currently, if I add the same person a second time, it just creates another one.
I'm searching for something like the "hasPersistendResultIds" option from the connectors.
Or do I need to check the entire chart if the ID is present, before adding it?

Cheers,
Timon

**Comment by Anthony-Johnson-i2** [comment]
Hi Timon

This issue might give you some clues 

https://github.com/i2group/analyze-connect-node-sdk/issues/16

In that the user was experiencing differences in behaviour between i2 Notebook and  i2 Analyst's Notebook Premium. 

Currently we do not have quite the same functionality in this area as we have in i2 Analyst's Notebook Premium but with each release we are bringing that closer.

You should however be able to get to a point where items are matched and 'Fused' on the chart so they display as a single item.

From our November 2023 release i2 Notebook now works with system matching rules to help minimise duplication, but did not do so before that.

How things interact is also dependent on the deployment pattern in use.

Can I ask:

What version of i2 Analyze you are doing this with?
What deployment pattern you are using (e.g. daod-opal, chart-storage-daod or information-store-daod-opal)?

If your deployment is also using an Information Store, and you are on our latest i2 Analyze 4.4.3  have you configured system match rules with source identifier matching documented[ here](https://docs.i2group.com/analyze/configuring_smr.html) ?  (Note: the steps are different depending on the  deployment pattern)
