### ISSUE TITLE
Seeded connector result

### ISSUE THREAD

**Issue by stvdo** [i2group/notebook-sdk#17]
Good afternoon,

I am using i2 Analyze 4.4.3 with fixpack and i2 containers 2.8.0.

I have a connector with person as a seed. In the output of the connector the seed is clickable. The link in this case is https://i2analyze.eia:9443/opal/#/records/4bMA8r9haErcWCgNFC25t1Tw6C. 

![image](https://github.com/i2group/notebook-sdk/assets/52672945/805f3a8d-d25d-4bd5-a9eb-0c756b5f3b0d)

When I click on the link I expect a page where I can see the details. But I got the error that the record is not longer available.
![image](https://github.com/i2group/notebook-sdk/assets/52672945/babf438a-e023-48b7-8542-7f13cdecab88)

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88 

I have chatted with Development on this and the reason for you getting the 'no longer available' message is that we are seeing the fact your seed has a record identifier and incorrectly assume that it is from the Information Store (IS) so provide a link to the IS version.
Note: This link is not to the version of the record that was the seed, but the submitted record in the IS.
Clicking the link does not  find it as it was not actually in the IS.

A bug issue has been raised to resolve this and I have allocated DT00322 to it.

Please note that as this is not actually an  i2 Notebook SDK issue  but is a problem with our production code . 

Cheers

**Comment by stvdo** [comment]
@Anthony-Johnson-i2 thank you very much for your reply!
