### ISSUE TITLE
Tool view command icon

### ISSUE THREAD

**Issue by chriiisiscoding** [i2group/notebook-sdk#19]
We defined a basic tool view command icon like so:

```javascript
  const toggle = api.commands.createToolViewToggleCommand(
    {
      id: "a5c92695-5811-472e-998a-48fe41195e42",
      name: "Our plugin",
      icon: {
        type: "inlineSvg",
        svg: '<svg viewBox="0 0 16 16"><circle cx="8" cy="8" r="4" /></svg>',
      }, ...
```

We would like to show a icon instead of a box (`rect`) or a `circle`. Is there an icon library that we can access? Or is there a way to bring in icons from elsewhere?

**Comment by Anthony-Johnson-i2** [comment]
Hi @chriiisiscoding 

I had a chat with development who gave the following information:

We do not supply an icon or image library but you can use your own as shown below.

You can see here that inlineSvg is not the only possible type.

[commands.IIcon type](https://i2group.github.io/notebook-sdk/api/notebook-sdk.commands.iicon.html?q=iicon)

For example:
```
{
  id: "xxxx",
  name: "Our plugin"
  icon: {
    type: "imageUrl"
    src: "http://url-to-image.png"
  }
}
```

`src` is equivalent to the same attribute in `<img src="url-to-image.png" />`

Cheers

**Comment by chriiisiscoding** [comment]
Thank you! We will give this a shot.

**Comment by Anthony-Johnson-i2** [comment]
Did this work for you @chriiisiscoding ?

**Comment by chriiisiscoding** [comment]
Yes, thank you!
