### ISSUE TITLE
How to package a plugin for the Analysis Studio container

### ISSUE THREAD

**Issue by stvdo** [i2group/notebook-sdk#2]
Good morning,

The plugin is running perfectly now. I am missing the instructions to package the plugin so that it can be used in the docker container of Analysis Studio. For the connectors it's descripted in detail, https://i2group.github.io/analyze-connect-node-sdk/guide/distribute-connector.html. 

I see the folder i2a-plugins and the plugin-references.json but have no idea what to put where.

Kind regards,
Steven

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88  (Steven)

I had a chat with one of our containers team and there is no packaging needed like you have with connectors, you just  provide the plugin files.

This is the page in the analyze-containers documentation that  explains things.

[Adding Plugins to your development environment](https://i2group.github.io/analyze-containers/content/develop_plugins.html)

Cheers

**Comment by stvdo** [comment]
Thank you very much!
