### ISSUE TITLE
About web client customization

### ISSUE THREAD

**Issue by RafaelCastilhoCastro** [i2group/notebook-sdk#3]
Hi team,
Sorry if that's not the right place to ask about this. We would like to know about the layout customization of the web client. We would like to do minor changes like adding our Logo to the page header for instance. Can you tell us if that is possible and if there's some documentation on it? If you could explain what would be required to make such customizations it would be much appreciated.

Thank you.

**Comment by Anthony-Johnson-i2** [comment]
Hi @RafaelCastilhoCastro 

You are fine asking this sort of question here ;-)

I checked in with the development team for you and unfortunately there are no options, either through application/server configuration or the SDK API, to customise the chrome of the i2 Notebook web application itself.

If you have support entitlement, you can raise a support [request](https://i2group.com/support-request)  referencing this issue and that can then be raised as a Request for Enhancement (RFE) .

Cheers.
