### ISSUE TITLE
Rebuild plugins

### ISSUE THREAD

**Issue by stvdo** [i2group/notebook-sdk#5]
Good afternoon,

I changed a react plugin and uploaded the build folder content to my config in an i2 Analyze (4.4.2) in the i2a-plugin folder/{plugin_name}. 

I changed among other things the SVG in the entrypoint.js. After I uploaded the files, I redeployed my config. But the plugin icon didn't change.

I also changed the version in public/plugin.json. But this didn't help neither.

And I did a clean deploy and a normal deploy, but nothing changed. 

I use i2 Analyze containers v 2.6.0.

What else can I do?

**Comment by stvdo** [comment]
Also the code in the ToolView.tsx is not updated. I changed the logic for the position, I ran 'npm run build', removed the static plugin folder on our demo server (2.7.0 instead of 2.6.0) and copied the new files to it. After this I deployed the config again. But the ToolView.tsx keeps the old code, while it was changed in the static plugin folder.

I tried also via incognito, but this didn't fix the issue.


![image](https://github.com/i2group/notebook-sdk/assets/52672945/47092c76-6130-4863-8880-101b0f34b8ba)
![image](https://github.com/i2group/notebook-sdk/assets/52672945/a2ef6ba7-8a82-4ef7-91d6-d07b283171c9)

On the server the code seems to be correct.
![image](https://github.com/i2group/notebook-sdk/assets/52672945/17d2bb19-1b13-4aa0-8bb2-0638ecf9d188)

**Comment by Tim-Mawson-i2** [comment]
Hello @sdorresteijn88, 

This feels like either a deployment or configuration issue of the plugin in i2 Analyze (https://github.com/i2group/analyze-containers/issues), or a caching problem. Can you first try making sure your browser cache is cleared? 

Tim

**Comment by stvdo** [comment]
Hello Tim,

Thanks for your response! I cleared the cache, this doesn't solve the issue.

Should I create a new issue there or can you forward it to a colleague?

**Comment by Tim-Mawson-i2** [comment]
For now, try raising an issue at https://github.com/i2group/analyze-containers/issues, I'll forward it to someone in that area of knowledge.

**Comment by Tim-Mawson-i2** [comment]
Hi @sdorresteijn88, could you list the exact contents of your `i2a-plugins/{plugin name}/static/js` folder? I noticed that your search for your "fixed" code returned matches in the `main.044b8a2b.js.map` file, I'm wondering why there isn't a match for the actual `main.044b8a2b.js` file. Also I notice that the file shown in the browser is `main.41eea9fd.js`, which makes me wonder if it's a copying/uploading issue to the i2a-plugins folder. You could also double check that i2a-plugins/{plugin name}/index.html has a `<script>` element pointing to the expected `./static/js/main.044b82b.js` file.

**Comment by stvdo** [comment]
Hi Tim,

See this printscreen for the static/js folder content.
![image](https://github.com/i2group/notebook-sdk/assets/52672945/83fa0983-6868-4a3d-acd2-5011b020bcb8)

Left the 'new code' on the server, right the 'new code' in the build folder of my local dev plugin.
![image](https://github.com/i2group/notebook-sdk/assets/52672945/76d7e7aa-352c-4cca-80da-f4cc3173c8ed)

Below the search in the src folder, the code is in the ToolView.tsx
![image](https://github.com/i2group/notebook-sdk/assets/52672945/ce8af6ad-6e92-455a-873a-dc4bb84ee896)

So something must go wrong during the local deployment. So I deployed again.
![image](https://github.com/i2group/notebook-sdk/assets/52672945/905e3180-e3c3-46a2-894b-3986f2a0f1bc)

And again the new code is only visible in the .map file.
![image](https://github.com/i2group/notebook-sdk/assets/52672945/01cae638-951d-4696-a89e-78623a428fc5)

I think I forgot to copy the index.html, the source is indeed wrong.
![image](https://github.com/i2group/notebook-sdk/assets/52672945/eb17a709-dbda-4e30-af8b-53b333cdc83d)

I changed the index.html and now it works again. 

Thanks a lot for your help!

**Comment by stvdo** [comment]
I forgot to close the issue.
