### ISSUE TITLE
Icon color

### ISSUE THREAD

**Issue by stvdo** [i2group/notebook-sdk#7]
Good morning,

It's possible to change the node color (background color) of an icon. Is it also possible to change the color of the icon easily (like it can be done in the ANBP)?

**Current situation**
![image](https://github.com/i2group/notebook-sdk/assets/52672945/ff965cb2-584a-4a34-85f8-e8635199f88a)

**Desired situation**
![image](https://github.com/i2group/notebook-sdk/assets/52672945/2cc6263e-1f4c-4fb6-9499-aed7777bcb93)

**Comment by Tim-Mawson-i2** [comment]
Hi @sdorresteijn88,

It is not possible at this time to re-color the icons.

Tim.

**Comment by Anthony-Johnson-i2** [comment]
Blimey that was a fast response @Tim-Mawson-i2  

Thank you.

**Comment by stvdo** [comment]
Thanks for your fast reply!
