### ISSUE TITLE
Add geospatial item to chart

### ISSUE THREAD

**Issue by stvdo** [i2group/notebook-sdk#8]
Good morning,

I have now added most properties to an entity and put them on the chart. However, I cannot figure out how to do this for the geospatial entities. Please can you help with this.

The Source is already a Geospatial object, so I expect that this can be easily added as a target property. 

My function in ToolView.tsx
```
const targetProperties: { [key: string]: data.PropertyValue } = {};
        for (const propertyType of entityType.propertyTypes) {
          
          const sourceProperty = event.properties.find((c: { typeId: any; }) => c.typeId === propertyType.analyzeId);
          if ( sourceProperty ) {
            console.log('Source', sourceProperty);
            console.log('Property', propertyType);
            if ( sourceProperty.value && (propertyType.logicalType === 'singleLineString' || propertyType.logicalType === 'suggestedFromList')){
              console.log('match');
              targetProperties[propertyType.id] = sourceProperty.value;
            } else {
              if ( propertyType.logicalType === 'geospatial'){
                debugger;
                //data.createGeoPoint();
                targetProperties[propertyType.id] = sourceProperty.value;
              }
            }
          }
        }
```

The error
![image](https://github.com/i2group/notebook-sdk/assets/52672945/80568c5e-dad0-4599-9bde-25626468ce60)

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88 

Have you had a look at the [ app.IValueFactory](https://i2group.github.io/notebook-sdk/api/notebook-sdk.app.ivaluefactory.html) that has  helper functions for creating a [data.IGeoPoint](https://i2group.github.io/notebook-sdk/api/notebook-sdk.data.igeopoint.html) object from either a pair of latitude and longitude values or from a  [data.IGeoPointData](https://i2group.github.io/notebook-sdk/api/notebook-sdk.data.igeopointdata.html) object.

![image](https://github.com/i2group/notebook-sdk/assets/98407720/6b35beac-688c-4451-a60d-972a8bdd79b0)


Cheers

**Comment by stvdo** [comment]
Hi @Anthony-Johnson-i2 ,

I have seen this in the connectors indeed. But I didn't get it to work in the plugin.

```
import {
  chart,
  data,
  records,
  schema,
  toolview,
} from '@i2analyze/notebook-sdk';
.....
targetProperties[propertyType.id] = data.createGeoPoint(sourceProperty.value.coordinates[1], sourceProperty.value.coordinates[0]);
```

This gives an error and I don't know what to import.

![image](https://github.com/i2group/notebook-sdk/assets/52672945/e7dc5530-8a46-404f-ad43-830e5171ae50)

![image](https://github.com/i2group/notebook-sdk/assets/52672945/136825c2-d6f4-4261-a617-0846567f46ab)

**Comment by Tim-Mawson-i2** [comment]
@sdorresteijn88  Using the value factory is the correct approach - however, note that `data` is just a typing namespace, there's no code (or at least very little) shipped with the @i2analyze/notebook-sdk, it's mostly just Typescript types. Instead, the value factory can be found on the mutations object that is passed to you in the `runXMutations` call, e.g.

```
api.runTrackedMutation((application, mutations) => {
  const geoPoint = mutations.valueFactory.createGeoPoint(lat, long);
  ...
});
```

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88  (Steven)  

With Tim's  last reply to you, did you manage to get this figured out?

If so, are you happy for this issue to be closed?

Cheers

**Comment by stvdo** [comment]
Morning @Tim-Mawson-i2 and @Anthony-Johnson-i2,

Thank you very much for your reply. That's the solution indeed, thanks a lot!
